---
actions:
  to: kubernetes/app/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{artifactId}}
  name: {{artifactId}}
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/name: {{artifactId}}
  sessionAffinity: None
  type: LoadBalancer